[phases.setup]
nixPkgs = ["...", "chromium", "chromedriver"]

[phases.build]
cmds = [
    "echo 'Chrome installed'",
    "which chromium",
    "which chromedriver"
]

[start]
cmd = "gunicorn --worker-class eventlet -w 1 app:app --bind 0.0.0.0:$PORT"
